use strum::FromRepr;

#[derive(FromRepr, Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Gp0Opcode {
    Nop = 0x00,
    ClearTextureCache = 0x01,
    FillRectangleInVram = 0x02,
    InterruptRequest = 0x1F,
    Monochrome3PointPolygonOpaque = 0x20,
    Monochrome3PointPolygonSemiTransparent = 0x22,
    Textured3PointPolygonOpaqueBlend = 0x24,
    Textured3PointPolygonOpaqueRaw = 0x25,
    Textured3PointPolygonSemiTransparentBlend = 0x26,
    Textured3PointPolygonSemiTransparentRaw = 0x27,
    Monochrome4PointPolygonOpaque = 0x28,
    Monochrome4PointPolygonSemiTransparent = 0x2A,
    Textured4PointPolygonOpaqueBlend = 0x2C,
    Textured4PointPolygonOpaqueRaw = 0x2D,
    Textured4PointPolygonSemiTransparentBlend = 0x2E,
    Textured4PointPolygonSemiTransparentRaw = 0x2F,
    Shaded3PointPolygonOpaque = 0x30,
    Shaded3PointPolygonSemiTransparent = 0x32,
    ShadedTextured3PointPolygonOpaqueBlend = 0x34,
    ShadedTextured3PointPolygonOpaqueRaw = 0x35,
    ShadedTextured3PointPolygonSemiTransparentBlend = 0x36,
    ShadedTextured3PointPolygonSemiTransparentRaw = 0x37,
    Shaded4PointPolygonOpaque = 0x38,
    Shaded4PointPolygonSemiTransparent = 0x3A,
    ShadedTextured4PointPolygonOpaqueBlend = 0x3C,
    ShadedTextured4PointPolygonOpaqueRaw = 0x3D,
    ShadedTextured4PointPolygonSemiTransparentBlend = 0x3E,
    ShadedTextured4PointPolygonSemiTransparentRaw = 0x3F,
    MonochromeLineOpaque = 0x40,
    MonochromeLineSemiTransparent = 0x42,
    ShadedLineOpaque = 0x50,
    ShadedLineSemiTransparent = 0x52,
    MonochromePolylineOpaque = 0x48,
    MonochromePolylineSemiTransparent = 0x4A,
    ShadedPolylineOpaque = 0x58,
    ShadedPolylineSemiTransparent = 0x5A,
    MonochromeRectangleVariableOpaque = 0x60,
    MonochromeRectangleVariableSemiTransparent = 0x62,
    TexturedRectangleVariableOpaqueBlend = 0x64,
    TexturedRectangleVariableOpaqueRaw = 0x65,
    TexturedRectangleVariableSemiTransparentBlend = 0x66,
    TexturedRectangleVariableSemiTransparentRaw = 0x67,
    DotRectangleOpaque = 0x68,
    DotRectangleSemiTransparent = 0x6A,
    Sprite8x8OpaqueBlend = 0x74,
    Sprite8x8OpaqueRaw = 0x75,
    Sprite8x8SemiTransparentBlend = 0x76,
    Sprite8x8SemiTransparentRaw = 0x77,
    Sprite16x16OpaqueBlend = 0x7C,
    Sprite16x16OpaqueRaw = 0x7D,
    Sprite16x16SemiTransparentBlend = 0x7E,
    Sprite16x16SemiTransparentRaw = 0x7F,
    CopyRectangleVramToVram = 0x80,
    CopyRectangleCpuToVram = 0xA0,
    CopyRectangleVramToCpu = 0xC0,
    DrawMode = 0xE1,
    TextureWindow = 0xE2,
    DrawingAreaTopLeft = 0xE3,
    DrawingAreaBottomRight = 0xE4,
    DrawingOffset = 0xE5,
    MaskBitSetting = 0xE6,
}

#[derive(FromRepr, Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Gp1Opcode {
    ResetGpu = 0x00,
    ResetCommandBuffer = 0x01,
    AcknowledgeInterrupt = 0x02,
    DisplayEnable = 0x03,
    DmaDirection = 0x04,
    DisplayVramStart = 0x05,
    DisplayHorizontalRange = 0x06,
    DisplayVerticalRange = 0x07,
    DisplayMode = 0x08,
    GetGpuInfo = 0x10,
}
