[package]
name = "playastation"
version.workspace = true
edition.workspace = true

[features]
default = []
software-renderer = ["dep:triple_buffer", "dep:crossbeam-utils"]

[dependencies]
tracing = { version = "0.1.44", default-features = false, features = ["attributes"] }

strum = { version = "0.28.0", default-features = false, features = ["derive"] }
bitflags = { version = "2.11.0", default-features = false }
modular-bitfield = "0.13.1"

fnv = { version = "1.0.7", default-features = false }
hashbrown = { version = "0.17.1", default-features = false }
slotmap = { version = "1.1.1", default-features = false }
smallvec = { version = "1.15.1", default-features = false }
smallbox = { version = "0.8.8", default-features = false, features = ["coerce"] }
yoke = { version = "0.8.2", default-features = false, features = ["alloc"] }
zerocopy = { version = "0.8.48", default-features = false, features = ["alloc"] }
zerocopy-derive = "0.8.48"

# Software renderer
triple_buffer = { version = "9.0.0", optional = true }
crossbeam-utils = { version = "0.8.21", optional = true }
